### ISSUE TITLE
Introduce ZoomPath for full zoom state representation.

### ISSUE THREAD

**Issue by andriytyurnikov** [zumly/zumly#3]
**Is your feature request related to a problem? Please describe.**
For integration with SPA routers it would be required to have full zoom-path (if single view may be represented in different locations of ZoomSpace)

**Describe the solution you'd like**
Simplest implementation would be a string representation like `/initial/zoomLevelOne/zoomLevelTwo`

**Describe alternatives you've considered**
Having same view with different names, is an acceptable work-around

**Additional context**
We could use an examples of nested zoom

**Comment by tinchox5** [comment]
Thanks @andriytyurnikov I'll put this on the roapmap asap
