### ISSUE TITLE
How to use with Vue?

### ISSUE THREAD

**Issue by rodrigomata** [zumly/zumly#4]
Can you please show an example of how to integrate with Vue?

**Comment by tinchox5** [comment]
Hi Rodrigo, sadly I'm really busy until end of next week to explain in detail how can VUE be integrated with Zumly. However, what you need to do is create a Vue component file as you usually do. Then, you need to export the component using the Vue CLI interface. You can read more about this at https://cli.vuejs.org/guide/build-targets.html#web-component
Finally, you can use the generated file in Zumly by adding the Vue component as a view, like this:
````
          import Zumly from './lib/zumly.min.mjs'
          import {yourVueComponent} from './yourVueComponent.js'

          const app = new Zumly({
            mount: '.mountPoint',
            initialView: 'yourVueComponent',
            views: {
              yourVueComponent
            }
          })

          app.init()
````
Please note, that Vue library is still needed for rendering that component, so you have to point the library in a `script` tag. This is well explained in the previous url.
Finally, you can mix Vue component with other kind of web-components.

I hope this short explanation can help you. In the future I'll post some examples.

**Comment by rodrigomata** [comment]
Hey! thanks a lot for the example! It's actually very useful
