### ISSUE TITLE
Zumly with SSGs

### ISSUE THREAD

**Issue by strategicallynicole** [zumly/zumly#6]
Hello!
I have been trying, unsuccessfully, to get Zircle, then Zumly, to work with any react-based SSG.  I have focused my efforts around Zumly and Gatsby, mostly.  Predictably, the error I receive is around Zumly's access to the canvas:

Cannot read property 'setAttribute' of null
./node_modules/zumly/dist/zumly.mjs:282
 // Prepare the instance:
      this.canvas = document.querySelector(this.mount);
      this.canvas.setAttribute('tabindex', 0);
      this.canvas.addEventListener('mouseup', this._onZoom, false);

Can you point me in a general research direction?  I'm not asking you to fix it for me, I just want to try to make this work in whatever way I can. 

Thanks so much!

**Comment by tinchox5** [comment]
Hi @strategicallynicole! Sorry for the inconveniences. Zircle is a vue plugin, so is not working outside vue ecosystem. Zumly is a js vanilla and it would work with others libraries. However Zumly is a concept right now, lot of work needs to be done to improve it. Having said that Zumly accepts any web-component. So, if your react ssg can produce a webcomponent, this can be used with Zumly
